#!/usr/bin/env node
// Differential: does this working tree produce EXACTLY what <base> produces?
//
//   node scripts/differential/run.mjs <base-ref> --corpus <dir|sources.json> [--gen 3000] [--show 3]
//
// Builds `outputs.ts` twice with esbuild — against <base-ref> (extracted with
// `git archive`, the working tree is never touched) and against this working
// tree — and compares every output (renders under both pairings and all three
// dialects, forum renders, exports to each target, effects, the HTML importer)
// over a corpus of real documents, the 547 KB fixture, and N documents
// generated by splicing BBCode fragments into slices of the real ones.
//
// Exit 0 when nothing differs, 1 when something does. This is the safety net
// for refactors that must not change output (docs/10-Semantic-Model-Plan.md).
//
// Needs `esbuild` and `jsdom` resolvable from the working directory (run it
// from the Miliastry monorepo root, or install both next to this repo).
//
// Corpus: a directory (every text file except .html/.md/.json; `X.html`
// beside `X.bbcode` feeds the HTML importer) or a JSON array of sources with
// `corpus-names.json` beside it (the parity kit's `corpus/`).

import { execFileSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, '../..')

const args = process.argv.slice(2)
const flag = (name, fallback) => {
  const i = args.indexOf(`--${name}`)
  return i === -1 ? fallback : args[i + 1]
}
const BASE = args[0]
const CORPUS = flag('corpus')
const GEN = Number(flag('gen', 3000))
const SHOW = Number(flag('show', 3))
if (!BASE || BASE.startsWith('--') || !CORPUS) {
  console.error('usage: node scripts/differential/run.mjs <base-ref> --corpus <dir|sources.json> [--gen N] [--show N]')
  process.exit(2)
}

const need = createRequire(join(process.cwd(), 'noop.js'))
const esbuild = need('esbuild')
const { JSDOM } = need('jsdom')

// ─── The two engines ─────────────────────────────────────────────────────────
const sha = execFileSync('git', ['-C', REPO, 'rev-parse', BASE], { encoding: 'utf8' }).trim()
const work = mkdtempSync(join(tmpdir(), 'quasar-differential-'))
const baseDir = join(work, 'base')
mkdirSync(baseDir)
execFileSync('sh', ['-c', `git -C "${REPO}" archive "${sha}" src | tar -x -C "${baseDir}"`])

async function bundle(name, engineDir) {
  const outfile = join(work, `${name}.cjs`)
  await esbuild.build({
    entryPoints: [join(HERE, 'outputs.ts')], bundle: true, platform: 'node', format: 'cjs', target: 'node20',
    outfile, alias: { '@q': join(engineDir, 'src/index.ts') }, logLevel: 'error',
  })
  return outfile
}

// The engines read the DOM globals at call time (HTML importer, a few
// renderer paths), so they are installed before either bundle loads.
const dom = new JSDOM('<!doctype html><html><body></body></html>')
for (const k of ['window', 'document', 'DOMParser', 'Node', 'HTMLElement', 'Element', 'NodeFilter', 'DocumentFragment']) {
  globalThis[k] = dom.window[k]
}
const req = createRequire(import.meta.url)
const before = req(await bundle('base', baseDir))
const after = req(await bundle('head', REPO))

// ─── The corpus ──────────────────────────────────────────────────────────────
const docs = []
if (statSync(CORPUS).isDirectory()) {
  const walk = (d) => {
    for (const f of readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const p = join(d, f.name)
      if (f.isDirectory()) { walk(p); continue }
      if (/\.(html|md|json)$/i.test(f.name)) continue
      const htmlPath = p.replace(/\.bbcode$/, '.html')
      docs.push({
        name: p.slice(CORPUS.length).replace(/^\//, ''),
        source: readFileSync(p, 'utf8'),
        html: p.endsWith('.bbcode') && existsSync(htmlPath) ? readFileSync(htmlPath, 'utf8') : null,
      })
    }
  }
  walk(CORPUS)
} else {
  const sources = JSON.parse(readFileSync(CORPUS, 'utf8'))
  const namesPath = join(dirname(CORPUS), 'corpus-names.json')
  const names = existsSync(namesPath) ? JSON.parse(readFileSync(namesPath, 'utf8')) : []
  sources.forEach((source, i) => docs.push({ name: names[i] ?? `${basename(CORPUS)}#${i}`, source, html: null }))
}
const fixture = join(REPO, '500KCharsTest')
if (existsSync(fixture)) docs.push({ name: '500KCharsTest', source: readFileSync(fixture, 'utf8'), html: null })
const real = docs.length

function mulberry32(a) {
  return () => {
    a |= 0; a = (a + 0x6D2B79F5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
// Fragments chosen to hit the osu!-specific paths: newline swallowing around
// every block, orphan and uppercase closers, rich titles, crossed tags.
const FRAGMENTS = ['x', ' ', '\n', '\n\n', '[b]', '[/b]', '[i]', '[/i]', '[box=T]', '[box=[b]R[/b] t]', '[box[/b] t]',
  '[/box]', '[spoilerbox]', '[/spoilerbox]', '[notice]', '[/notice]', '[list]', '[list=1]', '[*]', '[/list]',
  '[centre]', '[/centre]', '[center]', '[quote]', '[quote="a"]', '[/quote]', '[color=red]', '[color=#ff66ab]',
  '[/color]', '[size=150]', '[/size]', '[url=https://osu.ppy.sh]', '[/url]', '[img]https://a.b/c.png[/img]',
  '[code]', '[/code]', '[heading]', '[/heading]', '[B]', '[/B]',
  '[imagemap]\nhttps://a.b/i.png\n0 0 10 10 https://x T\n[/imagemap]', '&', '<', '"', "'"]
const pool = docs.filter((d) => d.source.length < 100_000)
for (let seed = 1; seed <= GEN && pool.length > 0; seed++) {
  const r = mulberry32(seed)
  const base = pool[Math.floor(r() * pool.length)].source
  const at = Math.floor(r() * base.length)
  let s = base.slice(at, at + 200 + Math.floor(r() * 2000))
  for (let i = 0; i < 1 + Math.floor(r() * 12); i++) {
    const p = Math.floor(r() * (s.length + 1))
    s = r() < 0.7
      ? s.slice(0, p) + FRAGMENTS[Math.floor(r() * FRAGMENTS.length)] + s.slice(p)
      : s.slice(0, p) + s.slice(p + 1 + Math.floor(r() * 8))
  }
  docs.push({ name: `gen-${seed}`, source: s, html: null })
}

// ─── Compare ─────────────────────────────────────────────────────────────────
const differing = {}
const samples = []
let compared = 0
for (const d of docs) {
  const a = before.outputs(d.source, d.html)
  const b = after.outputs(d.source, d.html)
  for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
    compared++
    if (a[k] === b[k]) continue
    const key = `${d.name.startsWith('gen-') ? 'generated' : 'real'} ${k}`
    differing[key] = (differing[key] ?? 0) + 1
    if (samples.filter((s) => s.key === key).length < SHOW) {
      const x = a[k] ?? '', y = b[k] ?? ''
      let j = 0
      while (j < x.length && x[j] === y[j]) j++
      samples.push({ key, doc: d.name, at: j, base: x.slice(Math.max(0, j - 80), j + 80), head: y.slice(Math.max(0, j - 80), j + 80) })
    }
  }
}

const total = Object.values(differing).reduce((n, c) => n + c, 0)
console.log(`differential ${sha.slice(0, 7)} → working tree: ${docs.length} documents (${real} real, ${docs.length - real} generated), ${compared} outputs, ${total} differ`)
for (const [k, n] of Object.entries(differing).sort()) console.log(`  ${n.toString().padStart(5)}  ${k}`)
for (const s of samples) console.log(`\n[${s.key}] ${s.doc} @${s.at}\n  base: ${JSON.stringify(s.base)}\n  head: ${JSON.stringify(s.head)}`)
process.exit(total === 0 ? 0 : 1)
